export const dataPerson = [
  {
    id: 1,
    position: "терапевт",
    price: 3800,
    name: "Анастасия",
    surname: "Варфоломеева",
    lastName: "Сергеевна",
    img: "https://vet.city/upload/iblock/19a/0xlwjwxaup09902dp3anw1f3bsdsqgwu.jpg",
  },
  {
    id: 2,
    position: "кардиолог",
    price: 4500,
    name: "Иван",
    surname: "Иванов",
    lastName: "Иванович",
    img: "https://vet.city/upload/iblock/799/4jmxy8462dpvnntv6dkb2hvq35quk476.jpg",
  },
  {
    id: 3,
    position: "стоматолог",
    price: 5000,
    name: "Елена",
    surname: "Петрова",
    lastName: "Александровна",
    img: "https://vet.city/upload/iblock/be3/h2lo8c2km1yug5zmci2ez360wsd859zg.jpg",
  },
  {
    id: 1,
    position: "терапевт",
    price: 3800,
    name: "Анастасия",
    surname: "Варфоломеева",
    lastName: "Сергеевна",
    img: "https://vet.city/upload/iblock/19a/0xlwjwxaup09902dp3anw1f3bsdsqgwu.jpg",
  },
  {
    id: 2,
    position: "кардиолог",
    price: 4500,
    name: "Иван",
    surname: "Иванов",
    lastName: "Иванович",
    img: "https://vet.city/upload/iblock/799/4jmxy8462dpvnntv6dkb2hvq35quk476.jpg",
  },
  {
    id: 3,
    position: "стоматолог",
    price: 5000,
    name: "Елена",
    surname: "Петрова",
    lastName: "Александровна",
    img: "https://vet.city/upload/iblock/be3/h2lo8c2km1yug5zmci2ez360wsd859zg.jpg",
  },
  {
    id: 1,
    position: "терапевт",
    price: 3800,
    name: "Анастасия",
    surname: "Варфоломеева",
    lastName: "Сергеевна",
    img: "https://vet.city/upload/iblock/19a/0xlwjwxaup09902dp3anw1f3bsdsqgwu.jpg",
  },
  {
    id: 2,
    position: "кардиолог",
    price: 4500,
    name: "Иван",
    surname: "Иванов",
    lastName: "Иванович",
    img: "https://vet.city/upload/iblock/799/4jmxy8462dpvnntv6dkb2hvq35quk476.jpg",
  },
  {
    id: 3,
    position: "стоматолог",
    price: 5000,
    name: "Елена",
    surname: "Петрова",
    lastName: "Александровна",
    img: "https://vet.city/upload/iblock/be3/h2lo8c2km1yug5zmci2ez360wsd859zg.jpg",
  },
];
