export const records = [
  {
    id: 1,
    type: "собака",
    gender: "мальчик",
    age: 6,
    name: "боб",
    sterilized: true,
    vaccinated: false,
  },
  {
    id: 2,
    type: "кошка",
    gender: "девочка",
    age: 3,
    name: "мурка",
    sterilized: true,
    vaccinated: true,
  },
  {
    id: 3,
    type: "хомяк",
    gender: "мальчик",
    age: 1,
    name: "пушок",
    sterilized: false,
    vaccinated: true,
  },
  {
    id: 4,
    type: "кролик",
    gender: "девочка",
    age: 2,
    name: "беляшка",
    sterilized: false,
    vaccinated: true,
  },
  {
    id: 5,
    type: "попугай",
    gender: "мальчик",
    age: 4,
    name: "киви",
    sterilized: false,
    vaccinated: false,
  },
  {
    id: 6,
    type: "черепаха",
    gender: "девочка",
    age: 5,
    name: "шелли",
    sterilized: false,
    vaccinated: false,
  },
  {
    id: 7,
    type: "собака",
    gender: "девочка",
    age: 7,
    name: "белла",
    sterilized: true,
    vaccinated: true,
  },
  {
    id: 8,
    type: "кошка",
    gender: "мальчик",
    age: 2,
    name: "тигра",
    sterilized: false,
    vaccinated: true,
  },
  {
    id: 9,
    type: "хомяк",
    gender: "девочка",
    age: 1,
    name: "пушистик",
    sterilized: false,
    vaccinated: true,
  },
  {
    id: 10,
    type: "кролик",
    gender: "мальчик",
    age: 3,
    name: "белый",
    sterilized: false,
    vaccinated: true,
  },
];
